# Generated by Django 4.0.1 on 2022-03-07 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Search',
        ),
    ]
