# Generated by Django 4.0.1 on 2022-03-07 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_delete_search'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startlong', models.IntegerField(blank=True, null=True, verbose_name='Longitude')),
                ('stratlat', models.IntegerField(blank=True, null=True, verbose_name='Latitude')),
                ('endlong', models.IntegerField(blank=True, null=True, verbose_name='Longitude')),
                ('endlat', models.IntegerField(blank=True, null=True, verbose_name='Latitude')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
