# Generated by Django 4.0.1 on 2022-03-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_location_stratlat_location_startlat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='endlat',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='location',
            name='endlong',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='location',
            name='startlat',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='location',
            name='startlong',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
    ]
