# Generated by Django 4.0.1 on 2022-03-07 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_location_endlat_alter_location_endlong_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='endlat',
        ),
        migrations.RemoveField(
            model_name='location',
            name='endlong',
        ),
        migrations.AlterField(
            model_name='location',
            name='startlat',
            field=models.FloatField(blank=True, null=True, verbose_name='Стартовая Широта'),
        ),
        migrations.AlterField(
            model_name='location',
            name='startlong',
            field=models.FloatField(blank=True, null=True, verbose_name='Стартовая Долгота'),
        ),
    ]
