# Generated by Django 4.0.1 on 2022-03-08 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_remove_location_endlat_remove_location_endlong_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartLoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startlong', models.FloatField(blank=True, null=True, verbose_name='Стартовая Долгота')),
                ('startlat', models.FloatField(blank=True, null=True, verbose_name='Стартовая Широта')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
