# Generated by Django 4.0.1 on 2022-03-08 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_startloc_delete_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airid', models.IntegerField(blank=True, max_length=150, null=True, verbose_name='airports id')),
                ('ident', models.CharField(blank=True, max_length=150, null=True, verbose_name='ident code')),
                ('type', models.CharField(blank=True, max_length=150, null=True, verbose_name='type by airports')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='name airports')),
                ('latitude_deg', models.CharField(blank=True, max_length=150, null=True, verbose_name='latitude')),
                ('longitude_deg', models.CharField(blank=True, max_length=150, null=True, verbose_name='longitude')),
                ('elevation_ft', models.CharField(blank=True, max_length=150, null=True, verbose_name='elevation')),
                ('continent', models.CharField(blank=True, max_length=150, null=True, verbose_name='continent')),
                ('iso_country', models.CharField(blank=True, max_length=150, null=True, verbose_name='iso_country')),
                ('iso_region', models.CharField(blank=True, max_length=150, null=True, verbose_name='iso_region')),
                ('municipality', models.CharField(blank=True, max_length=150, null=True, verbose_name='municipality')),
                ('scheduled_service', models.CharField(blank=True, max_length=150, null=True, verbose_name='scheduled_service')),
                ('gps_code', models.CharField(blank=True, max_length=150, null=True, verbose_name='gps_code')),
                ('iata_code', models.CharField(blank=True, max_length=150, null=True, verbose_name='iata_code')),
                ('local_code', models.CharField(blank=True, max_length=150, null=True, verbose_name='local_code')),
                ('home_link', models.URLField(blank=True, null=True, verbose_name='home_link')),
                ('wikipedia_link', models.URLField(blank=True, null=True, verbose_name='wikipedia_link')),
                ('keywords', models.CharField(blank=True, max_length=150, null=True, verbose_name='keywords')),
            ],
        ),
    ]
