# Generated by Django 4.0.1 on 2022-03-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_airports_airid'),
    ]

    operations = [
        migrations.AddField(
            model_name='startloc',
            name='endlat',
            field=models.FloatField(blank=True, null=True, verbose_name='Конечная Широта'),
        ),
        migrations.AddField(
            model_name='startloc',
            name='endlong',
            field=models.FloatField(blank=True, null=True, verbose_name='Конечная Долгота'),
        ),
        migrations.AlterField(
            model_name='airports',
            name='airid',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='airports id'),
        ),
        migrations.AlterField(
            model_name='airports',
            name='continent',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='continent'),
        ),
        migrations.AlterField(
            model_name='airports',
            name='elevation_ft',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='elevation'),
        ),
        migrations.AlterField(
            model_name='airports',
            name='gps_code',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='gps_code'),
        ),
        migrations.AlterField(
            model_name='airports',
            name='iata_code',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='iata_code'),
        ),
        migrations.AlterField(
            model_name='airports',
            name='ident',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='ident code'),
        ),
        migrations.AlterField(
            model_name='airports',
            name='iso_country',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='iso_country'),
        ),
        migrations.AlterField(
            model_name='airports',
            name='iso_region',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='iso_region'),
        ),
        migrations.AlterField(
            model_name='airports',
            name='keywords',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='keywords'),
        ),
        migrations.AlterField(
            model_name='airports',
            name='latitude_deg',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='latitude'),
        ),
        migrations.AlterField(
            model_name='airports',
            name='local_code',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='local_code'),
        ),
        migrations.AlterField(
            model_name='airports',
            name='longitude_deg',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='longitude'),
        ),
        migrations.AlterField(
            model_name='airports',
            name='municipality',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='municipality'),
        ),
        migrations.AlterField(
            model_name='airports',
            name='name',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='name airports'),
        ),
        migrations.AlterField(
            model_name='airports',
            name='scheduled_service',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='scheduled_service'),
        ),
        migrations.AlterField(
            model_name='airports',
            name='type',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='type by airports'),
        ),
    ]
