# Generated by Django 4.0.1 on 2022-03-17 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_places_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='name',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Название места'),
        ),
    ]
