# Generated by Django 4.0.1 on 2022-03-17 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_places_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Airports',
        ),
    ]
