# Generated by Django 4.0.1 on 2022-03-20 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_delete_airports'),
    ]

    operations = [
        migrations.AddField(
            model_name='routecoordinates',
            name='name_from',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Откуда'),
        ),
        migrations.AddField(
            model_name='routecoordinates',
            name='name_to',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Куда'),
        ),
        migrations.AlterField(
            model_name='places',
            name='name',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Поиск'),
        ),
    ]
