# Generated by Django 4.0.1 on 2022-03-22 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0017_routecoordinates_name_from_routecoordinates_name_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='name',
            field=models.CharField(blank=True, default='Minsk', max_length=400, verbose_name='Поиск'),
        ),
        migrations.AlterField(
            model_name='routecoordinates',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routs', to=settings.AUTH_USER_MODEL),
        ),
    ]
