# Generated by Django 4.0.1 on 2022-03-25 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_routecoordinates_name_from_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=400, null=True, verbose_name='countries code')),
                ('name', models.CharField(blank=True, max_length=400, null=True, verbose_name='countries name')),
                ('continent', models.CharField(blank=True, max_length=400, null=True, verbose_name='countries continent')),
                ('wikipedia_link', models.URLField(blank=True, null=True, verbose_name='home_link')),
                ('keywords', models.CharField(blank=True, max_length=400, null=True, verbose_name='elevation')),
            ],
        ),
    ]
