# Generated by Django 4.0.1 on 2022-03-29 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_routecoordinates_kash_routecoordinates_transport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routecoordinates',
            name='kash',
            field=models.TextField(blank=True, null=True, verbose_name='Кэш для построения маршрута в истории'),
        ),
    ]
