# Generated by Django 4.0.1 on 2022-03-29 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_routecoordinates_kash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routecoordinates',
            name='kash',
            field=models.JSONField(blank=True, null=True, verbose_name='Кэш для построения маршрута в истории'),
        ),
    ]
